[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Single Page App routing: serve index.html for any route
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
